### ISSUE TITLE
Stuck on dlopen ctypes lib with anaconda

### ISSUE THREAD

**Issue by platipodium** [jreniel/geomesh#5]
Any ideas for the following dlopen issue?

```
File "/Volumes/Kea/Applications/miniconda3/lib/python3.7/site-packages/jigsawpy-0.0.2-py3.7.egg/jigsawpy/libsaw.py", line 68, in <module>
    jlib = ct.cdll.LoadLibrary(str(jlibname))
  File "/Volumes/Kea/Applications/miniconda3/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/Volumes/Kea/Applications/miniconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
```

**Comment by jreniel** [comment]
Are you on a mac? I think this is on the jigsaw library side.

**Comment by jreniel** [comment]
I am preparing a Vagrantfile so you can load the environment on any machine.

**Comment by jreniel** [comment]
@platipodium I have added a Vagrantfile, so you can load the development environment on any computer, no matter the OS or version. It is very easy to do so. You will need to have installed [VirtualBox])(https://www.virtualbox.org/) and [Vagrant](https://www.vagrantup.com/). Once you have installed this development dependencies, clone the repo and do 
```bash
vagrant up --provision
```
This will install an environment with everything that you need to test/develop. 
One this installation is done, you can do 
```bash
vagrant ssh
```
And your shell will change for the vagrant shell I prepared. The vagrant directory will be synced real time with the host directory, so all changes and additions you make on the host will be immediately reflected on the vagrant container, so you can use vagrant as a drop-in replacement for the shell you are currently using. I tested it a on a MacBookPro 2016 and it seems to be working, let me know if you have any further issues or questions.
-Jaime
P.S. The problem seems to be the way the libraries are being called on the jigsaw library, I'll have to take this to Darren Engwirda or test myself and create a PR for them. In the meantime, I think Vagrant should help.

**Comment by jreniel** [comment]
MacOSX is not supported at the time. Use Linux, or the Windows Subsystem for Linux. To test the software on a Mac, you may use the Vagrant method.

**Comment by platipodium** [comment]
I ran the examples provided successfully on Linux (with regular install).  Thanks for looking into this.
