### ISSUE TITLE
How to reduce memory footprint

### ISSUE THREAD

**Issue by platipodium** [jreniel/geomesh#8]
With a rather small testcase from my own data along a river dataset, I encountered out-of-memory errors 

`Traceback (most recent call last):
  File "/home/lemmen/devel/geomesh/.geomesh_env/lib/python3.7/site-packages/geomesh-0.0.2-py3.7.egg/geomesh/pslg.py", line 158, in vert2
AttributeError: 'PlanarStraightLineGraph' object has no attribute 
'_PlanarStraightLineGraph__vert2'`

`MemoryError: Unable to allocate array with shape (16000, 28000) and data type float64`

What can be done on the data input side or parameters to jigsaw/geomesh to reduce the memory footprint?

**Comment by jreniel** [comment]
Hi,
It's trying to allocate a (16000 x 28000) array which is actually a huge array. This program is not computationally expensive, but it is memory expensive. This is because the MultiPolygons that make up the PSLG will be of the native resolution of the input DEM. We can downsample the DEMs inside the program but I've avoided doing that by default because it degrades the output quality. Example 3 processes 252 tiles which includes about 52 tiles of 1/9 arcsec resolution, and it consumes a substantial amount of memory, jutnit works. The way to handle out of memory situations is by increasing the swap. You have two options. You can use systemd-swap to dynamically increase the swapfile for you as needed, or you can put a spare hdd on tje computer with a fairly large swap partition. That is, you need in increase your virtual memory if you want high quality results. If you don't care about high quality, then there's a method to downsample the DEM inside the program (it doesn't actually affect the file, this is all done in-memory). If you could e-mail me a link to your test file, I'd like to give it a try.

Thanks!
-J

**Comment by jreniel** [comment]
One possible reason for this huge array is that maybe your input has multiple bands, and so far the program assumes a single band file. I don't really know if that is the case, but if it is, I can provide a fix.

**Comment by jreniel** [comment]
I'm open to suggestions on how to reduce the memory footprint, hopefully without resulting input PSLG distortion.

**Comment by jreniel** [comment]
Also, can you post an image of the PSLG? We can check to make sure that the program is not generating garbage by inspecting the output of the pslg.make_plot(show=True)

**Comment by jreniel** [comment]
I am implementing a buffering system.

**Comment by jreniel** [comment]
Completed implementation to solve this issue.
